#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Parse a RealSense D435 wall/ceiling capture session and derive pattern assets
useful for Blender simulation.

Expected session layout (generated by the capture script):
    wall_capture/
      session_YYYYmmdd_HHMMSS/
        capture_meta.json
        capture_summary.json
        frames.jsonl
        left_on/*.png
        right_on/*.png
        left_off/*.png
        right_off/*.png

What this script produces:
    pattern_analysis/
      left/ and right/
        median_on.png
        median_off.png
        mean_on.png
        mean_off.png
        pattern_diff_raw.png
        pattern_diff_raw.npy
        pattern_flatfield.png
        pattern_flatfield.npy
        pattern_lcn.png
        pattern_lcn.npy
        peaks.json
        stats.json
      analysis_summary.json

Core idea:
    1) Build median / mean images for ON and OFF phases separately.
    2) Extract projector contribution with ON - OFF.
    3) Remove coarse illumination / vignetting using flat-field division.
    4) Optionally compute local contrast normalization (LCN).
    5) Detect stable local maxima as approximate dot centers.

Note on geometry:
    Intel's public D435 datasheet gives official depth-camera mechanical depth of
    25 mm and depth start point for D435/D435i of -4.2 mm from the front cover
    glass. The exact rear-shell-to-sensor-center distance is not explicitly
    published. Therefore this script uses the *best official approximation*:

        rear_to_depth_origin_mm = 25.0 - 4.2 = 20.8 mm

    If you measured 1025 mm from the rear wall of the camera body to the plane,
    then the estimated distance from the D435 depth origin to the plane is:

        1025.0 - 20.8 = 1004.2 mm

    This is appropriate for Blender camera-origin style geometry, but it should
    not be marketed as an exact factory-published sensor-center distance.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Dict, List, Tuple

import cv2
import numpy as np


# ---------------------------- official / inferred constants ----------------------------

D435_CAMERA_DEPTH_MM = 25.0
D435_FRONT_GLASS_TO_DEPTH_START_MM = 4.2  # official magnitude for D435/D435i
D435_REAR_TO_DEPTH_ORIGIN_MM = D435_CAMERA_DEPTH_MM - D435_FRONT_GLASS_TO_DEPTH_START_MM  # 20.8 mm


# ---------------------------- IO helpers ----------------------------

def read_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_json(path: Path, obj: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)


def ensure_dir(path: Path):
    path.mkdir(parents=True, exist_ok=True)


def select_session(root: Path, session: str) -> Path:
    if session.lower() == "latest":
        sessions = sorted([p for p in root.glob("session_*") if p.is_dir()])
        if not sessions:
            raise FileNotFoundError(f"No session_* directories found under {root}")
        return sessions[-1]
    path = root / session
    if not path.is_dir():
        raise FileNotFoundError(f"Session not found: {path}")
    return path


def sorted_pngs(folder: Path) -> List[Path]:
    return sorted(folder.glob("*.png"))


def load_u8_grayscale(path: Path) -> np.ndarray:
    img = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
    if img is None:
        raise RuntimeError(f"Failed to read image: {path}")
    if img.ndim != 2:
        raise RuntimeError(f"Expected single-channel grayscale image: {path}")
    if img.dtype != np.uint8:
        # Capture protocol is fixed to y8, but keep the script defensive.
        if img.dtype == np.uint16:
            img = np.clip(img / 256.0, 0, 255).astype(np.uint8)
        else:
            img = np.clip(img, 0, 255).astype(np.uint8)
    return img


def save_png_u8(path: Path, img: np.ndarray):
    img_u8 = np.clip(img, 0, 255).astype(np.uint8)
    ok = cv2.imwrite(str(path), img_u8, [cv2.IMWRITE_PNG_COMPRESSION, 1])
    if not ok:
        raise RuntimeError(f"Failed to write PNG: {path}")


# ---------------------------- statistics / transforms ----------------------------

def robust_normalize_to_u8(x: np.ndarray, p_lo: float = 1.0, p_hi: float = 99.0) -> np.ndarray:
    x = np.asarray(x, dtype=np.float32)
    lo = float(np.percentile(x, p_lo))
    hi = float(np.percentile(x, p_hi))
    if not np.isfinite(lo):
        lo = float(np.min(x))
    if not np.isfinite(hi):
        hi = float(np.max(x))
    if hi <= lo + 1e-12:
        return np.zeros_like(x, dtype=np.uint8)
    y = (x - lo) / (hi - lo)
    y = np.clip(y, 0.0, 1.0)
    return np.round(y * 255.0).astype(np.uint8)


def build_stack(paths: List[Path]) -> np.ndarray:
    if not paths:
        raise ValueError("Empty path list")
    frames = [load_u8_grayscale(p) for p in paths]
    return np.stack(frames, axis=0)


def compute_phase_statistics(stack: np.ndarray) -> dict:
    stack_f = stack.astype(np.float32)
    per_frame_mean = stack_f.mean(axis=(1, 2))
    per_frame_std = stack_f.std(axis=(1, 2))
    per_frame_sat = (stack == 255).mean(axis=(1, 2))
    per_frame_zero = (stack == 0).mean(axis=(1, 2))

    return {
        "num_frames": int(stack.shape[0]),
        "image_hw": [int(stack.shape[1]), int(stack.shape[2])],
        "global_mean_intensity": float(stack_f.mean()),
        "global_std_intensity": float(stack_f.std()),
        "per_frame_mean": {
            "mean": float(per_frame_mean.mean()),
            "std": float(per_frame_mean.std()),
            "min": float(per_frame_mean.min()),
            "max": float(per_frame_mean.max()),
        },
        "per_frame_std": {
            "mean": float(per_frame_std.mean()),
            "std": float(per_frame_std.std()),
            "min": float(per_frame_std.min()),
            "max": float(per_frame_std.max()),
        },
        "saturated_ratio": {
            "mean": float(per_frame_sat.mean()),
            "std": float(per_frame_sat.std()),
            "min": float(per_frame_sat.min()),
            "max": float(per_frame_sat.max()),
        },
        "zero_ratio": {
            "mean": float(per_frame_zero.mean()),
            "std": float(per_frame_zero.std()),
            "min": float(per_frame_zero.min()),
            "max": float(per_frame_zero.max()),
        },
    }


def median_mean_from_paths(paths: List[Path]) -> Tuple[np.ndarray, np.ndarray, dict]:
    stack = build_stack(paths)
    med = np.median(stack, axis=0).astype(np.float32)
    mean = stack.mean(axis=0).astype(np.float32)
    stats = compute_phase_statistics(stack)
    return med, mean, stats


def make_raw_projector_signal(median_on: np.ndarray, median_off: np.ndarray) -> np.ndarray:
    diff = median_on.astype(np.float32) - median_off.astype(np.float32)
    return np.clip(diff, 0.0, None)


def flat_field_normalize(raw: np.ndarray, sigma_px: float, eps: float = 1e-6) -> Tuple[np.ndarray, np.ndarray]:
    raw = raw.astype(np.float32)
    lowfreq = cv2.GaussianBlur(raw, ksize=(0, 0), sigmaX=sigma_px, sigmaY=sigma_px)
    corrected = raw / (lowfreq + eps)
    return corrected, lowfreq


def local_contrast_normalize(raw: np.ndarray, sigma_px: float, eps: float = 1e-6) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    raw = raw.astype(np.float32)
    mu = cv2.GaussianBlur(raw, ksize=(0, 0), sigmaX=sigma_px, sigmaY=sigma_px)
    sq = cv2.GaussianBlur(raw * raw, ksize=(0, 0), sigmaX=sigma_px, sigmaY=sigma_px)
    var = np.clip(sq - mu * mu, 0.0, None)
    sigma = np.sqrt(var + eps)
    lcn = (raw - mu) / (sigma + eps)
    return lcn, mu, sigma


def detect_peaks(
    score: np.ndarray,
    threshold_percentile: float = 99.5,
    nms_radius_px: int = 2,
    border_px: int = 4,
    max_peaks: int = 50000,
) -> List[dict]:
    score = np.asarray(score, dtype=np.float32)
    h, w = score.shape
    thr = float(np.percentile(score, threshold_percentile))

    # Non-maximum suppression via dilation.
    k = 2 * nms_radius_px + 1
    kernel = np.ones((k, k), np.uint8)
    dil = cv2.dilate(score, kernel)
    peak_mask = (score >= thr) & (score >= dil - 1e-12)

    if border_px > 0:
        peak_mask[:border_px, :] = False
        peak_mask[-border_px:, :] = False
        peak_mask[:, :border_px] = False
        peak_mask[:, -border_px:] = False

    ys, xs = np.where(peak_mask)
    vals = score[ys, xs]
    order = np.argsort(-vals)
    if max_peaks is not None:
        order = order[:max_peaks]

    peaks = []
    for idx in order:
        peaks.append({
            "x": int(xs[idx]),
            "y": int(ys[idx]),
            "score": float(vals[idx]),
        })
    return peaks


# ---------------------------- camera / geometry helpers ----------------------------

def extract_intrinsics(capture_meta: dict, side: str) -> dict | None:
    key = "IR_LEFT" if side.lower() == "left" else "IR_RIGHT"
    streams = capture_meta.get("streams", {})
    intr = streams.get(key)
    return intr


def build_geometry_summary(rear_to_surface_mm: float | None, capture_meta: dict | None) -> dict:
    result = {
        "official_camera_depth_mm": D435_CAMERA_DEPTH_MM,
        "official_front_glass_to_depth_start_mm": D435_FRONT_GLASS_TO_DEPTH_START_MM,
        "best_official_rear_to_depth_origin_mm": D435_REAR_TO_DEPTH_ORIGIN_MM,
        "notes": [
            "Intel publicly specifies D435 overall depth = 25 mm and depth start point = -4.2 mm from front cover glass.",
            "Exact rear-shell-to-physical-sensor-center distance is not explicitly published in the public datasheet.",
            "This script therefore uses rear_to_depth_origin_mm = 20.8 mm as the best official approximation.",
        ],
    }
    if rear_to_surface_mm is not None:
        result["measured_rear_to_surface_mm"] = float(rear_to_surface_mm)
        result["estimated_depth_origin_to_surface_mm"] = float(rear_to_surface_mm - D435_REAR_TO_DEPTH_ORIGIN_MM)
        result["estimated_front_glass_to_surface_mm"] = float(rear_to_surface_mm - D435_CAMERA_DEPTH_MM)
    if capture_meta is not None:
        result["selected_laser_power_on"] = capture_meta.get("selected_laser_power_on")
        result["sensor_state_after_lock"] = capture_meta.get("sensor_state_after_lock")
    return result


# ---------------------------- main analysis per side ----------------------------

def analyze_one_side(
    session_dir: Path,
    side: str,
    flatfield_sigma_px: float,
    lcn_sigma_px: float,
    peak_percentile: float,
) -> dict:
    assert side in ("left", "right")

    on_dir = session_dir / f"{side}_on"
    off_dir = session_dir / f"{side}_off"
    if not on_dir.is_dir() or not off_dir.is_dir():
        raise FileNotFoundError(f"Missing phase folders for side '{side}'")

    on_paths = sorted_pngs(on_dir)
    off_paths = sorted_pngs(off_dir)
    if not on_paths or not off_paths:
        raise RuntimeError(f"No PNG files found for side '{side}'")

    median_on, mean_on, on_stats = median_mean_from_paths(on_paths)
    median_off, mean_off, off_stats = median_mean_from_paths(off_paths)

    raw = make_raw_projector_signal(median_on, median_off)
    flatfield, lowfreq = flat_field_normalize(raw, sigma_px=flatfield_sigma_px)
    lcn, lcn_mu, lcn_sigma = local_contrast_normalize(raw, sigma_px=lcn_sigma_px)

    peaks = detect_peaks(
        score=flatfield,
        threshold_percentile=peak_percentile,
        nms_radius_px=2,
        border_px=4,
        max_peaks=50000,
    )

    out_dir = session_dir / "pattern_analysis" / side
    ensure_dir(out_dir)

    save_png_u8(out_dir / "median_on.png", median_on)
    save_png_u8(out_dir / "median_off.png", median_off)
    save_png_u8(out_dir / "mean_on.png", mean_on)
    save_png_u8(out_dir / "mean_off.png", mean_off)
    save_png_u8(out_dir / "pattern_diff_raw.png", robust_normalize_to_u8(raw, 0.5, 99.8))
    save_png_u8(out_dir / "pattern_flatfield.png", robust_normalize_to_u8(flatfield, 1.0, 99.7))
    save_png_u8(out_dir / "pattern_lcn.png", robust_normalize_to_u8(lcn, 1.0, 99.7))
    save_png_u8(out_dir / "pattern_lowfreq.png", robust_normalize_to_u8(lowfreq, 0.5, 99.8))

    np.save(out_dir / "pattern_diff_raw.npy", raw.astype(np.float32))
    np.save(out_dir / "pattern_flatfield.npy", flatfield.astype(np.float32))
    np.save(out_dir / "pattern_lcn.npy", lcn.astype(np.float32))
    np.save(out_dir / "pattern_lowfreq.npy", lowfreq.astype(np.float32))
    np.save(out_dir / "median_on.npy", median_on.astype(np.float32))
    np.save(out_dir / "median_off.npy", median_off.astype(np.float32))

    peaks_payload = {
        "num_peaks": int(len(peaks)),
        "threshold_percentile": float(peak_percentile),
        "peaks": peaks,
    }
    write_json(out_dir / "peaks.json", peaks_payload)

    stats = {
        "side": side,
        "num_on_frames": len(on_paths),
        "num_off_frames": len(off_paths),
        "on_stats": on_stats,
        "off_stats": off_stats,
        "raw_pattern": {
            "mean": float(raw.mean()),
            "std": float(raw.std()),
            "max": float(raw.max()),
            "p50": float(np.percentile(raw, 50.0)),
            "p95": float(np.percentile(raw, 95.0)),
            "p99": float(np.percentile(raw, 99.0)),
            "nonzero_ratio": float((raw > 0).mean()),
        },
        "flatfield_pattern": {
            "mean": float(flatfield.mean()),
            "std": float(flatfield.std()),
            "max": float(flatfield.max()),
            "p95": float(np.percentile(flatfield, 95.0)),
            "p99": float(np.percentile(flatfield, 99.0)),
        },
        "lcn_pattern": {
            "mean": float(lcn.mean()),
            "std": float(lcn.std()),
            "min": float(lcn.min()),
            "max": float(lcn.max()),
            "p95": float(np.percentile(lcn, 95.0)),
            "p99": float(np.percentile(lcn, 99.0)),
        },
        "detected_peaks": {
            "count": int(len(peaks)),
            "density_peaks_per_mpix": float(len(peaks) / (raw.shape[0] * raw.shape[1]) * 1e6),
        },
        "recommended_for_blender": {
            "projection_texture_png": str((out_dir / "pattern_flatfield.png").name),
            "projection_texture_npy": str((out_dir / "pattern_flatfield.npy").name),
            "canonical_camera_side": "left",
            "notes": [
                "Use pattern_flatfield as the first approximation of projector texture.",
                "pattern_diff_raw keeps absolute ON-OFF intensity without coarse shading compensation.",
                "pattern_lcn emphasizes local dot structure and is useful for debugging, not usually as the final projection texture.",
            ],
        },
    }
    write_json(out_dir / "stats.json", stats)
    return stats


# ---------------------------- CLI ----------------------------

def make_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Build Blender-ready projector pattern assets from a D435 wall_capture session"
    )
    p.add_argument("--root", type=str, default="wall_capture", help="Root folder that contains session_* subdirectories")
    p.add_argument("--session", type=str, default="latest", help="Session folder name or 'latest'")
    p.add_argument(
        "--rear_to_surface_mm",
        type=float,
        default=1025.0,
        help="Measured distance from the rear wall of the D435 body to the capture plane (mm)",
    )
    p.add_argument("--flatfield_sigma_px", type=float, default=25.0, help="Gaussian sigma for coarse illumination compensation")
    p.add_argument("--lcn_sigma_px", type=float, default=9.0, help="Gaussian sigma for local contrast normalization")
    p.add_argument("--peak_percentile", type=float, default=99.5, help="Percentile threshold for stable peak detection")
    return p


def main():
    args = make_parser().parse_args()

    root = Path(args.root)
    session_dir = select_session(root, args.session)

    capture_meta_path = session_dir / "capture_meta.json"
    capture_meta = read_json(capture_meta_path) if capture_meta_path.is_file() else None

    left_stats = analyze_one_side(
        session_dir=session_dir,
        side="left",
        flatfield_sigma_px=args.flatfield_sigma_px,
        lcn_sigma_px=args.lcn_sigma_px,
        peak_percentile=args.peak_percentile,
    )
    right_stats = analyze_one_side(
        session_dir=session_dir,
        side="right",
        flatfield_sigma_px=args.flatfield_sigma_px,
        lcn_sigma_px=args.lcn_sigma_px,
        peak_percentile=args.peak_percentile,
    )

    intrinsics = {
        "left": extract_intrinsics(capture_meta, "left") if capture_meta is not None else None,
        "right": extract_intrinsics(capture_meta, "right") if capture_meta is not None else None,
    }

    summary = {
        "session_dir": str(session_dir),
        "geometry": build_geometry_summary(args.rear_to_surface_mm, capture_meta),
        "intrinsics": intrinsics,
        "outputs": {
            "left": str(session_dir / "pattern_analysis" / "left"),
            "right": str(session_dir / "pattern_analysis" / "right"),
        },
        "left": left_stats,
        "right": right_stats,
        "recommended_blender_start": {
            "use_side": "left",
            "texture_png": str(session_dir / "pattern_analysis" / "left" / "pattern_flatfield.png"),
            "texture_npy": str(session_dir / "pattern_analysis" / "left" / "pattern_flatfield.npy"),
            "estimated_depth_origin_to_plane_mm": float(args.rear_to_surface_mm - D435_REAR_TO_DEPTH_ORIGIN_MM),
            "notes": [
                "Start with the left-side flat-field corrected pattern texture.",
                "Later, when projector geometry is recovered, warp this texture into the projector image plane.",
                "The current script does not recover projector intrinsics or projector-to-camera extrinsics.",
            ],
        },
    }
    write_json(session_dir / "pattern_analysis" / "analysis_summary.json", summary)

    print(f"Session: {session_dir}")
    print(f"Estimated rear->depth-origin: {D435_REAR_TO_DEPTH_ORIGIN_MM:.3f} mm")
    print(f"Estimated depth-origin->plane: {args.rear_to_surface_mm - D435_REAR_TO_DEPTH_ORIGIN_MM:.3f} mm")
    print(f"Outputs written to: {session_dir / 'pattern_analysis'}")


if __name__ == "__main__":
    main()
